### ISSUE TITLE
AuthService: Wywala się na niepoprawnych wartościach tokena

### ISSUE THREAD

**Issue by Udiknedormin** [mateusz59861/PZ-gr.2#76]
W przypadku kiedy poprawny token dla "test" to:
{"access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NTk1ODU2NTAsIm5iZiI6MTU1OTU4NTY1MCwianRpIjoiZGQ1MTNjNDItMGM5OC00ZmI1LTllNmMtMDA5NWEwMjUwMzU3IiwiZXhwIjoxNTU5NTg2NTUwLCJpZGVudGl0eSI6InRlc3QiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.Kquc3sL0Av0NSuDNwHckIDKJL0sg54ilvhEXdrPwUfg"}

AuthService, kiedy dostaje:
{"access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NTk1ODU2NTAsIm5iZiI6MTU1OTU4NTY1MCwianRpIjoiZGQ1MTNjNDItMGM5OC00ZmI1LTllNmMtMDA5NWEwMjUwMzU3IiwiZXhwIjoxNTU5NTg2NTUwLCJpZGVudGl0eSI6InRlc3QiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.Kquc3sL0Av0NSuDNwHckIDKJL0sg54ilvhEXdrPwUfgeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NTk1ODU2NTAsIm5iZiI6MTU1OTU4NTY1MCwianRpIjoiZGQ1MTNjNDItMGM5OC00ZmI1LTllNmMtMDA5NWEwMjUwMzU3IiwiZXhwIjoxNTU5NTg2NTUwLCJpZGVudGl0eSI6InRlc3QiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.Kquc3sL0Av0NSuDNwHckIDKJL0sg54ilvhEXdrPwUfg"}

Rzuca:

Traceback (most recent call last):
  File "$HOME/.local/lib/python3.6/site-packages/jwt/api_jws.py", line 204, in _load
    signature = base64url_decode(crypto_segment)
  File "$HOME/.local/lib/python3.6/site-packages/jwt/utils.py", line 42, in base64url_decode
    return base64.urlsafe_b64decode(input)
  File "/usr/lib/python3.6/base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/.local/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "$HOME/.local/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "$HOME/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "$HOME/.local/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "$HOME/.local/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "$HOME/.local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 102, in wrapper
    verify_jwt_in_request()
  File "$HOME/.local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 31, in verify_jwt_in_request
    jwt_data = _decode_jwt_from_request(request_type='access')
  File "$HOME/.local/lib/python3.6/site-packages/flask_jwt_extended/view_decorators.py", line 266, in _decode_jwt_from_request
    decoded_token = decode_token(encoded_token, csrf_token)
  File "$HOME/.local/lib/python3.6/site-packages/flask_jwt_extended/utils.py", line 81, in decode_token
    encoded_token, verify=False, algorithms=config.algorithm
  File "$HOME/.local/lib/python3.6/site-packages/jwt/api_jwt.py", line 84, in decode
    payload, _, _, _ = self._load(jwt)
  File "$HOME/.local/lib/python3.6/site-packages/jwt/api_jws.py", line 206, in _load
    raise DecodeError('Invalid crypto padding')
jwt.exceptions.DecodeError: Invalid crypto padding
127.0.0.1 - - [03/Jun/2019 20:16:17] "GET /v1/protected HTTP/1.1" 500 -

**Comment by Udiknedormin** [comment]
Dla "AyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1NTk1ODU2NTAsIm5iZiI6MTU1OTU4NTY1MCwianRpIjoiZGQ1MTNjNDItMGM5OC00ZmI1LTllNmMtMDA5NWEwMjUwMzU3IiwiZXhwIjoxNTU5NTg2NTUwLCJpZGVudGl0eSI6InRlc3QiLCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.Kquc3sL0Av0NSuDNwHckIDKJL0sg54ilvhEXdrPwUfg" tak samo.

**Comment by mateusz59861** [comment]
Chyba tak samo jak w #74, w najnowszej wersji nie wywala się na tym:
![obraz](https://user-images.githubusercontent.com/14963295/58827809-382ecc80-8644-11e9-99a7-8b7cfe964f2e.png)
